-- Reference only. Do not execute this template unchanged.
-- Use bind_nlp_identities.sql after the matching
-- Microsoft Entra managed identities have been mapped into PostgreSQL.
--
-- GRANT olga_dml_writer TO nlp_api_database_principal;
-- GRANT olga_nlp_worker TO nlp_worker_database_principal;
